// Builds src/content/legal.ts VERBATIM from the Markdown legal documents in docs/legal/.
// Usage: node scripts/build-legal.mjs   (then commit both). The app shows identical text;
// update the Markdown sources, never the generated TS.
import { readFileSync, writeFileSync } from 'node:fs'

const DOCS = [
  { slug: 'terms', path: '/terms', file: 'docs/legal/terms.md' },
  { slug: 'privacy', path: '/privacy', file: 'docs/legal/privacy.md' },
  { slug: 'subscription', path: '/subscription-terms', file: 'docs/legal/subscription-terms.md' },
]

function parse(md) {
  const lines = md.replace(/\r\n/g, '\n').split('\n')
  const doc = { title: '', updated: '', intro: '', blocks: [] }
  let para = [], list = null, seenIntro = false
  const flushPara = () => { if (para.length) { const text = para.join(' ').trim(); if (!seenIntro && doc.updated) { doc.intro = text; seenIntro = true } else doc.blocks.push({ type: 'p', text }); para = [] } }
  const flushList = () => { if (list) { doc.blocks.push({ type: 'ul', items: list }); list = null } }
  for (const raw of lines) {
    const line = raw.trimEnd()
    if (!line.trim()) { flushPara(); flushList(); continue }
    const h1 = line.match(/^# (.+)$/); if (h1) { doc.title = h1[1].trim(); continue }
    const upd = line.match(/^\*(Last updated .+?)\*$/); if (upd) { doc.updated = upd[1].trim(); continue }
    const h2 = line.match(/^## (.+)$/); if (h2) { flushPara(); flushList(); doc.blocks.push({ type: 'h', text: h2[1].trim() }); continue }
    const li = line.match(/^- (.+)$/); if (li) { flushPara(); (list ??= []).push(li[1].trim()); continue }
    flushList(); para.push(line.trim())
  }
  flushPara(); flushList()
  if (!doc.title || !doc.updated || !doc.intro || doc.blocks.length < 5) throw new Error('unexpected structure in document: ' + doc.title)
  return doc
}

const docs = DOCS.map((d) => ({ slug: d.slug, path: d.path, ...parse(readFileSync(d.file, 'utf8')) }))
  .map(({ slug, title, path, updated, intro, blocks }) => ({ slug, title, path, updated, intro, blocks }))

const out = `/**
 * GROW legal text — GENERATED VERBATIM from docs/legal/*.md by scripts/build-legal.mjs.
 * The app shows the identical text; the two must not drift. Edit the Markdown, then run
 * \`node scripts/build-legal.mjs\`. Do not edit this file by hand.
 */

export type LegalBlock = { type: "h"; text: string } | { type: "p"; text: string } | { type: "ul"; items: string[] };

export interface LegalDoc {
  slug: string;
  title: string;
  path: string;
  updated: string;
  intro: string;
  blocks: LegalBlock[];
}

export const legalDocs: LegalDoc[] = ${JSON.stringify(docs, null, 2)};

export const legalBySlug = Object.fromEntries(legalDocs.map((d) => [d.slug, d])) as Record<string, LegalDoc>;
`
writeFileSync('src/content/legal.ts', out)
console.log(docs.map((d) => `${d.slug}: "${d.title}" · ${d.updated} · ${d.blocks.length} blocks`).join('\n'))
